Odkazy na půjčovnu vodáckého materiálu
bosancz/interni-sekce pull request #58
Opened 2023-11-02 15:31 UTC by Grejdy

# Změny
V postranním menu přibyla rozbalovací nabídka „půjčovna“ obsahující odkazy na půjčovnu vodáckého vybavení.
 - 

# Testovací scénář

1. Otevři si test.bosan.cz a obnov stránku.
    - Windows: `CTRL + F5`
    - Mac: `⌘ Cmd + ⇧ Shift + R`
2. Zkontroluj, že to tak je, a že odkazy fungují a odkazují na rozumné místo. Můžeš mi i dát názor, jestli jsou popisy odkazů takhle dobré a jestli by nebylo lepší sjednotit dizajn odkazů s nadřazenými prvky, nebo jinak upravit.

 Po otestování vždy napiš feedback, buď `Approve review`, nebo `Request changes`. Návod zde: [Jak na testování](https://github.com/bosancz/bosan.cz/wiki/Jak-na-testov%C3%A1n%C3%AD%3F)

2023-11-02 16:17 UTC, DavidTvrdy requested changes
Názor na grafiku odkazů nemám, ani na to, jestli nechat pouze "Půjčovna" s odkazem na ten formulář nebo rozdělit na dva odkazy (jak je teď).
Všechny odkazy bych ale každopádně otevíral na nové kartě.

2023-11-02 16:17 UTC, DavidTvrdy commented on frontend/src/app/core/components/admin-menu/admin-menu.component.html
Odkazy otevírat na nové kartě

2023-11-02 18:59 UTC, Grejdy commented on frontend/src/app/core/components/admin-menu/admin-menu.component.html
Good point

2023-11-02 19:16 UTC, Grejdy commented
Ještě jsem to změnil z jednoduchého odkazu na něco podobnějšího zbytku toho panelu.

2023-11-02 19:19 UTC, Grejdy commented
Když na to teď koukám, možná by dávalo větší smysl, dát to až nad ten odkaz na veřejnou…

2023-11-03 11:22 UTC, DavidTvrdy requested changes
Odkazy jsou takhle hezčí.
Ale všimnul jsem si, že na mobilu po kliknutí někam v menu se menu zavře. Pro rozklikávací položku je to nežádoucí - menu by se nemělo zavírat, protože ho pak musím znovu otevřít, než mžu kliknout na jeden z odkazů.

2023-11-03 15:29 UTC, Grejdy commented
>Ale všimnul jsem si, že na mobilu po kliknutí někam v menu se menu zavře. Pro rozklikávací položku je to nežádoucí - menu by se nemělo zavírat, protože ho pak musím znovu otevřít, než mžu kliknout na jeden z odkazů.

Jo, to je hloupý. Nějak se mi to ale nedaří napravit. Zkoušel jsem různé internetové návody, jak tohle řešit u ionicových menu, ale nic nefunguje.
Je to menu vůbec z ionicu, nebo je to něco jinýho? A kde je do toho webu implementovaný (resp. kde se to bude dát konfigurovat) @SmallhillCZ ?

2023-11-14 07:58 UTC, Grejdy commented
Tak, s půjčovnou to aktuálně vypadá tak, že se pravděpodobně bude nějakým způsobem zjednodušovat, takže tuhle záležitost bych uspal, než to ve vodáckém výboru vymyslíme a pak možná přestane dávat smysl mít tam dva odkazy, takže se tím vyřeší i problém se zavíráním menu při rozbalení nabídky.

2026-01-05 10:28 UTC, SmallhillCZ commented
tohle je hodně starý, zavírám, kdyžtak se ozvěte, kdyby to mělo mít nějakou budoucnost

2026-01-05 10:28 UTC, closed without merging